app:
    vim:
        desc:   ViM editor
        ubuntu: vim-full
        fedora: vim-enhanced vim-X11
    ruby:
        desc:   ruby interpreter
        ubuntu: ruby rubygems irb ruby-dev
        fedora: ruby rubygems irb ruby-devel
    firebird:
        desc:   Firebird super server
        ubuntu: firebird2.1-super firebird2.1-dev flamerobin
        fedora: firebird-superserver firebird-filesystem firebird-devel flamerobin
gems:
    capistrano: capistrano
    cucumber: webrat cucumber
