app:
    vim:
        desc:   ViM editor
        ubuntu: vim-full vim-gtk ctags
        fedora: vim-enhanced vim-X11 ctags
    firebird:
        desc:   Firebird super server
        ubuntu: firebird2.1-super firebird2.1-dev flamerobin
        fedora: firebird-superserver firebird-filesystem firebird-devel flamerobin
    postgres:
        desc:   PostgreSQL server
        ubuntu: postgresql libpq-dev pgadmin3
        fedora: postgresql postgresql-server postgresql-devel pgadmin3
    libxml2:
        desc:   XML2 library - required by Cucumber
        ubuntu: libxml2 libxml2-dev
        fedora: libxml2 libxml2-devel
    libxslt1:   
        desc:   XSLT library - required by Cucumber
        ubuntu: libxslt1.1 libxslt1-dev
        fedora: libxslt libxslt-devel
gem:
    capistrano: capistrano
    cucumber: webrat cucumber rspec rspec-rails ZenTest rcov
    vim: vim-ruby
    markaby: markaby
    mongrel: mongrel
    haml: haml hpricot
    rails: rails
    postgres: ruby-pg pg postgres

